/* Hildana.M
 * FastFood_U2_A4
 * This program calculates the total cost for a person's order 
 * March/09/2018
 */

/**
 *
 * @author Hildana
 */
import java.text.DecimalFormat;
public class FormFastFood_U2_A4 extends javax.swing.JFrame {

    /**
     * Creates new form FormFastFood_U2_A4
     */
    public FormFastFood_U2_A4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelTitle2 = new javax.swing.JLabel();
        labelBurger = new javax.swing.JLabel();
        textBurgerNumber = new javax.swing.JTextField();
        labelFries = new javax.swing.JLabel();
        textFriesNumber = new javax.swing.JTextField();
        labelDrink = new javax.swing.JLabel();
        textDrinkNumber = new javax.swing.JTextField();
        labelEnterAmount = new javax.swing.JLabel();
        textAmountTendered = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelOutputTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelOutputFinal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelOutputChange = new javax.swing.JLabel();
        labelOutputTax = new javax.swing.JLabel();
        labelBurgerPrice = new javax.swing.JLabel();
        labelFriesPrice = new javax.swing.JLabel();
        labelDrinkPrice = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Welcome!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labelTitle.setFont(new java.awt.Font("Algerian", 0, 55)); // NOI18N
        labelTitle.setText("Welcome!");

        labelTitle2.setFont(new java.awt.Font("Algerian", 0, 26)); // NOI18N
        labelTitle2.setText("Please enter your order ");

        labelBurger.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelBurger.setText("Number Of Burger:");

        textBurgerNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textBurgerNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBurgerNumberActionPerformed(evt);
            }
        });

        labelFries.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelFries.setText("Number Of Fries: ");

        textFriesNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textFriesNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFriesNumberActionPerformed(evt);
            }
        });

        labelDrink.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDrink.setText("Number Of Drinks: ");

        textDrinkNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textDrinkNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDrinkNumberActionPerformed(evt);
            }
        });

        labelEnterAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelEnterAmount.setText("Amount Tendered:");

        textAmountTendered.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        buttonCalculate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Total Before Taxes:");

        labelOutputTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOutputTotal.setText("...........");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tax:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Final Total:");

        labelOutputFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOutputFinal.setText("...........");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Change:");

        labelOutputChange.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOutputChange.setText("...........");

        labelOutputTax.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelOutputTax.setText("............");

        labelBurgerPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelBurgerPrice.setText("Burgers are $2.49 each");

        labelFriesPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelFriesPrice.setText("Fries are $1.89 each ");

        labelDrinkPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelDrinkPrice.setText("Drinks are $0.99 each");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastfood_u2_a4/burger.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel9)))
                                .addGap(140, 140, 140)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(184, 184, 184)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelOutputChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelOutputFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelOutputTax, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(110, 110, 110)
                                        .addComponent(labelOutputTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBurger)
                                    .addComponent(labelFries)
                                    .addComponent(labelDrink)
                                    .addComponent(labelEnterAmount))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFriesNumber)
                                    .addComponent(textDrinkNumber)
                                    .addComponent(textBurgerNumber)
                                    .addComponent(textAmountTendered, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addGap(137, 137, 137)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFriesPrice)
                                    .addComponent(labelDrinkPrice)
                                    .addComponent(labelBurgerPrice)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(labelTitle)))
                .addGap(0, 111, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(labelTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(1, 1, 1)
                .addComponent(labelTitle2)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBurgerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBurger)
                    .addComponent(labelBurgerPrice))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelFries))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFriesNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(labelFriesPrice))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDrinkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDrink)
                    .addComponent(labelDrinkPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnterAmount)
                    .addComponent(textAmountTendered, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelOutputTotal)
                    .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOutputTax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(labelOutputFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelOutputChange, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textBurgerNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBurgerNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBurgerNumberActionPerformed

    private void textFriesNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFriesNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFriesNumberActionPerformed

    private void textDrinkNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDrinkNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDrinkNumberActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        
        //declaring variables 
        int burger, fries, drink;
        double burgerPrice = 2.49, friesPrice = 1.89, drinkPrice = 0.99, tender;
        double totalBurgerP, totalFriesP, totalDrinkP;
        double total, tax, finalTotal, change;
        
        //take the text entered by the user 
        burger = (int) Double.parseDouble (textBurgerNumber.getText());
        fries = (int) Double.parseDouble (textFriesNumber.getText());
        drink = (int) Double.parseDouble (textDrinkNumber.getText());
        tender = Double.parseDouble (textAmountTendered.getText());
        
        //total price for the burgers, fries, and drink
        totalBurgerP = burger*burgerPrice;
        totalFriesP = fries*friesPrice;
        totalDrinkP = drink*drinkPrice;
        
        //calculation for cost 
        total = totalBurgerP + totalFriesP + totalDrinkP;
        tax = 0.13 * (totalBurgerP + totalFriesP + totalDrinkP);
        finalTotal = tax + total;
        change = tender - finalTotal;
        
        //round to two decimal places 
        DecimalFormat round = new DecimalFormat ("###.##");
        
        //display those text on the labels 
        labelOutputTotal.setText("$" + round.format(total));
        labelOutputTax.setText("$" + round.format (tax));
        labelOutputFinal.setText("$" + round.format (finalTotal));
        labelOutputChange.setText("$" + round.format (change));
        
      
    }//GEN-LAST:event_buttonCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFastFood_U2_A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFastFood_U2_A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFastFood_U2_A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFastFood_U2_A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFastFood_U2_A4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBurger;
    private javax.swing.JLabel labelBurgerPrice;
    private javax.swing.JLabel labelDrink;
    private javax.swing.JLabel labelDrinkPrice;
    private javax.swing.JLabel labelEnterAmount;
    private javax.swing.JLabel labelFries;
    private javax.swing.JLabel labelFriesPrice;
    private javax.swing.JLabel labelOutputChange;
    private javax.swing.JLabel labelOutputFinal;
    private javax.swing.JLabel labelOutputTax;
    private javax.swing.JLabel labelOutputTotal;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JTextField textAmountTendered;
    private javax.swing.JTextField textBurgerNumber;
    private javax.swing.JTextField textDrinkNumber;
    private javax.swing.JTextField textFriesNumber;
    // End of variables declaration//GEN-END:variables
}
